# Generated by Django 3.2 on 2021-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='imginp',
            field=models.ImageField(default='', upload_to='main_page/images'),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
