# Generated by Django 3.2 on 2021-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20210802_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('desc_type', models.IntegerField(default=0)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
