# Generated by Django 3.2 on 2021-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('work', models.CharField(default='', max_length=150)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('zip_code', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
