# Generated by Django 3.2 on 2021-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_auto_20210922_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trousers',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('real_price', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='main_page/images')),
                ('image2', models.ImageField(default='', upload_to='main_page/images')),
                ('image3', models.ImageField(default='', upload_to='main_page/images')),
                ('image4', models.ImageField(default='', upload_to='main_page/images')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=3000)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TShirts',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('real_price', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='main_page/images')),
                ('image2', models.ImageField(default='', upload_to='main_page/images')),
                ('image3', models.ImageField(default='', upload_to='main_page/images')),
                ('image4', models.ImageField(default='', upload_to='main_page/images')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=3000)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
